
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Thu Jan 28 00:11:41 CET 2016
//----------------------------------------------------

package syntactical;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 29;
  public static final int GE = 35;
  public static final int UMINUS = 50;
  public static final int INTEGER = 4;
  public static final int LPAREN = 19;
  public static final int INT = 12;
  public static final int ASSERT = 52;
  public static final int FOR = 45;
  public static final int MINUS = 27;
  public static final int RPAREN = 20;
  public static final int NOT = 38;
  public static final int AND = 36;
  public static final int FIELD = 8;
  public static final int SEMICOLON = 17;
  public static final int LT = 32;
  public static final int NIL = 47;
  public static final int OR = 37;
  public static final int COMMA = 16;
  public static final int CLASS = 6;
  public static final int PLUS = 26;
  public static final int IF = 41;
  public static final int ASSIGN = 39;
  public static final int DOT = 25;
  public static final int ID = 2;
  public static final int LE = 33;
  public static final int FLOATING = 5;
  public static final int EOF = 0;
  public static final int BOOLEAN = 14;
  public static final int RETURN = 46;
  public static final int ARRAYSYMBOL = 40;
  public static final int METHOD = 9;
  public static final int TEST = 51;
  public static final int TRUE = 48;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int NEQ = 31;
  public static final int VOID = 15;
  public static final int EQ = 30;
  public static final int LBRACK = 21;
  public static final int TIMES = 28;
  public static final int ELSE = 43;
  public static final int LBRACE = 23;
  public static final int RBRACK = 22;
  public static final int WHILE = 44;
  public static final int CONSTRUCTOR = 10;
  public static final int FLOAT = 13;
  public static final int THEN = 42;
  public static final int RBRACE = 24;
  public static final int EXTENDS = 7;
  public static final int STRING = 3;
  public static final int FIXTURE = 53;
  public static final int FALSE = 49;
  public static final int AS = 18;
  public static final int GT = 34;
}

